---
version: 2
kitchen-executor: &kitchen-executor
    docker:
        #- image: ubuntu:14.04
        - image: circleci/python:latest

set-dev-creds: &set-dev-creds
    name: creds for dev
    command: |
        echo 'this is dev'
        echo "POTATO=dev" >> vars.txt

set-stage-creds: &set-stage-creds
    name: creds for stage
    command: |
        echo 'this is stage'
        echo "POTATO=stage" >> vars.txt

dev-prep-steps: &dev-prep-steps
    steps:
        - run:
              <<: *set-dev-creds
        - run:
              name: 'preppin for dev'
              command: |
                  echo 'preppin for dev'
                  #apt-get update
                  #apt-get install ca-certificates -y
        - run:
              name: save env
              command: |
                  cat vars.txt
                  cat vars.txt > ~/.envvars

        - persist_to_workspace:
              root: ~/
              paths:
                  - .envvars


stage-prep-steps: &stage-prep-steps
    steps:
        - run:
              <<: *set-stage-creds
        - run:
              name: 'preppin for stage'
              command: |
                  echo 'preppin for stage'
                  #apt-get update
                  #apt-get install ca-certificates -y
        - run:
              name: save env
              command: |
                  cat vars.txt
                  cat vars.txt > ~/.envvars

        - persist_to_workspace:
              root: ~/
              paths:
                  - .envvars

plan-steps: &plan-steps
    steps:
        - attach_workspace:
              at: ~/
        - run: cat ~/.envvars >> vars.txt
        - run:
              name: planning
              command: |
                echo "now I'm planning hey"
                ls -al ~
                cat vars.txt

deploy-steps: &deploy-steps
    steps:
        - attach_workspace:
              at: ~/
        - run: cat ~/.envvars >> vars.txt
        - run:
              name: deploy
              command: |
                echo "now I'm deploying hey"
                ls -al ~
                cat vars.txt

jobs:
    prep-dev:
        <<: *kitchen-executor
        working_directory: ~/
        <<: *dev-prep-steps

    prep-stage:
        <<: *kitchen-executor
        working_directory: ~/
        <<: *stage-prep-steps

    plan:
        <<: *kitchen-executor
        working_directory: ~/
        <<: *plan-steps

    deploy:
        <<: *kitchen-executor
        working_directory: ~/
        <<: *deploy-steps

filter_merge: &filter_merge
    filters:
        branches:
            only:
                - master

workflows:
    version: 2
    provision-dev:
        jobs:
            - prep-dev:
                  <<: *filter_merge
            - plan:
                  requires:
                      - prep-dev
            - deploy:
                  requires:
                      - plan
    provision-stage:
        jobs:
            - prep-stage:
                  <<: *filter_merge
            - plan:
                  requires:
                      - prep-stage
            - deploy:
                  requires:
                      - plan
